### ISSUE TITLE
Helper.decode8bit not a function

### ISSUE THREAD

**Issue by scramble45** [JulianWowra/node-pdu#1]
Code:
var pdu = require('node-pdu');

```
pdu.parse('06810458759100100200005D242454657374696E672061206E6577206D65737361676520746F2074656C6974203C39323338343938333E3C32393338393530383233393035242424243E2C3C3933383539303832333530393E2C3C39323338353039383233353E2323');
```

Error:
    /node_code/node_modules/node-pdu/PDU/Data/Part.js:76
                text = Helper.decode8bit(hex);
                              ^

```
TypeError: Helper.decode8bit is not a function
    at Function.Part.parse (/node_code/node_modules/node-pdu/PDU/Data/Part.js:76:27)
    at Function.Data.parse (/node_code/node_modules/node-pdu/PDU/Data.js:56:20)
    at Function.Helper.initVars (/node_code/node_modules/node-pdu/PDU/Helper.js:285:26)
    at Function.PDU.parse (/node_code/node_modules/node-pdu/pdu.js:122:19)
    at Object.<anonymous> (/node_code/pdutest.js:3:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

not sure on this one.

**Comment by jackkum** [comment]
Thank you for feedback. 
I fixed it. 
I'll write autotests.

**Comment by scramble45** [comment]
Working better,

Something doesn't look right with this data I think. Im pretty new to pdu stuff, any pointers would be great.

    Deliver {
      _sca:
       SCA {
         _type: Type { _type: 0, _plan: 1 },
         _size: 10,
         _phone: '4085571900',
         _encoded: '4085571900',
         _isAddress: true },
      _type: Deliver { _rp: 0, _udhi: 0, _srr: 0, _rd: 0, _mti: 0, _vpf: 2 },
      _pid: PID { _pid: 1, _indicates: 0, _type: 29 },
      _dcs:
       DCS {
         _encodeGroup: 2,
         _dataEncoding: 4,
         _compressedText: true,
         _alphabet: 1,
         _useMessageClass: false,
         _classMessage: 0,
         _discardMessage: false,
         _storeMessage: false,
         _storeMessageUCS2: false,
         _dataCodingAndMessageClass: false,
         _messageIndication: false,
         _messageIndicationType: false },
      _scts: SCTS { _time: NaN },
      _address:
       SCA {
         _type: Type { _type: 1, _plan: 1 },
         _size: 2,
         _phone: '00',
         _encoded: '00',
         _isAddress: true },
      _udl: 103,
      _ud:
       Data {
         _parts:
          [ Part {
              _data: '2061206E6577206D65737361676520746F2074656C6974203C39323338343938333E3C32393338393530383233393035242424243E2C3C3933383539303832333530393E2C3C39323338353039383233353E2323',
              _size: 84,
              _parent: [Circular],
              _text: '\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000' } ],
         _isUnicode: false,
         _pdu: [Circular],
         _data: '\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000',
         _size: 84 } }

**Comment by jackkum** [comment]
Found one typo in Helper.decode8Bit and strange value in time stamp
06810458759100100200005D24**2454657374696E**672061206E6577206D65737361676520746F2074656C6974203C39323338343938333E3C32393338393530383233393035242424243E2C3C3933383539303832333530393E2C3C39323338353039383233353E2323
Time stamp: `56/45/2042 37:47:96` `Date.parse()` return NaN

**Comment by jackkum** [comment]
For get text from pdu you can do this:
```javacript
var res = pdu.parse('06810...353039383233353E2323');
var data = res.getData(); // Data object
console.log(data.getText());
```

**Comment by jackkum** [comment]
For join parts of message you can call `append`
```javascript
var parts = [
  '06810...353039383233353E2323',
  '06810...353039383233353E2323',
  // ...
];

var sms = undefined;
parts.forEach(function(str){
  if( ! sms){
    sms = pdu.parse(str);
  } else {
    sms.append(pdu.parse(str));
  }
});
var data = sms.getData();
console.log(data.getText());
```

Validation in append function will throw error if that is not part of same message.
After adding a part, they will be sorted, so no matter in what order they was added.

**Comment by scramble45** [comment]
working slightly better, trying to get text from : 06810458759100100200000431323334 - which should output: 1234 and I get no output.

**Comment by jackkum** [comment]
What device generate you this PDU string? 
https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/
06810458759100 - SMSC
10 (0001 0000 bin) - PDU type (3,4 bits is unused)
020000 - OA
5D (93 dec) - PID
? - Data Coding Scheme
? - Service Center Time Stamp
? -  User Data Length
242454657374696E672061206E6577206D65737361676520746F2074656C6974203C39323338343938333E3C32393338393530383233393035242424243E2C3C3933383539303832333530393E2C3C39323338353039383233353E2323 - this is a correct ascii

PDU Types:
1 0 MS -> SC SC -> MS
**0 0** SMS-DELIVER REPORT SMS-DELIVER
1 0 SMS-COMMAND SMS-STATUS REPORT
0 1 SMS-SUBMIT SMS-SUBMIT REPORT
1 1 RESERVED

![image004](https://cloud.githubusercontent.com/assets/2418167/17919630/8754e126-6a01-11e6-9244-a0a88aa4f599.gif)

**Comment by scramble45** [comment]
Ah your right, not sure why but this telit CE910-D is generating either a incomplete or malformed PDU. No idea why.

**Comment by jackkum** [comment]
Need some time to learn more about the problem.

**Comment by KillerJulian** [comment]
Hello @scramble45, 👋 
a new major version has just been released. Please check if your problem still exists. Update the problem description/logs if possible. Please give feedback.

Thank you!

**Comment by JulianWowra** [comment]
Closed because no reply to my message.
If your concern persists, please reply with a comment.
